export const SHOW_USERS = "SHOW_USERS";
export const SHOW_USERS_SUCCESS = "SHOW_USERS_SUCCESS";
export const SHOW_USERS_FAILURE = "SHOW_USERS_FAILURE";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const LIKE_USER = "LIKE_USER";
